config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'


  match '/sign_up', to: 'users#new', via: 'get'
  match '/profile', to: 'users#show', via: 'get'
  match '/profile/*path', to: 'users#show', via: 'get'
  
  resources :users, only: [:new, :show]

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sessions, only: [:create, :destroy]
      resources :users, only: [:new, :create, :update, :destroy]
      resources :friendship_requests, only: [:index, :create, :destroy]
      resources :friendships, only: [:create, :destroy]
      resources :questions, only: [:create, :show]
      resources :answers, only: [:update]

      match 'signout', to: 'sessions#destroy', via: 'delete'
      match 'users/current_user', to: 'users#get_current_user', via: 'get'
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	#before_action :redirect_to_profile, except: :profile

	def index
	end

	def test
	end

	def profile
	end

	private
	def redirect_to_profile
		if signed_in?
			redirect_to profile_path
		end
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<div class="otr-home" ng-app="publicapp" ng-controller="SignInController">
	
	<div class="otr-home-logo">
		<h1 id="logo">Off the Record</h1>
	</div>

	<div class="otr-home-controls">
		
		<div class="otr-slate-w">
			<form name="signUpForm" ng-submit="signIn(signin)">
				<div class="otr-input-group">
					<input type="text" placeholder="email / username" ng-model="signin.email">
					<input type="password" placeholder="password" ng-model="signin.password">
				</div>
				
				<ul class="otr-validation-errors">
					<li ng-repeat="err in errors">{{err}}</li>
				</ul>

				<br/>
				<button type="submit" class="otr-btn-primary lg">
					<%= icon('magic') %>&nbsp;&nbsp;Log In
				</button>
			</form>
			<br/><br/>
			<p>Or, join the fun</p>
			<%= link_to sign_up_path, class: "otr-btn-secondary md" do %> 
			<%= icon('hand-o-right') %> Sign Up 
			<% end %> 
		</div>

	</div>

</div>

<script>
	$(document).ready(function() {
		$("#logo").arctext({radius: 400});
	});
</script>